media:
  input: public/assets
  output: /assets

content:
  - name: jotting
    label: Jotting
    type: collection
    path: src/content/jotting/zh-cn
    format: yaml-frontmatter
    view:
      primary: title
      sort: [ 'timestamp', 'title' ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: timestamp
        label: Timestamp
        type: date
        required: true
      - name: series
        label: Series
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Body
        type: rich-text

  - name: note
    label: Note
    type: collection
    path: src/content/note/zh-cn
    format: yaml-frontmatter
    view:
      primary: title
      sort: [ 'timestamp', 'title' ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: timestamp
        label: Timestamp
        type: date
        required: true
      - name: series
        label: Series
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: description
        label: Description
        type: text
      - name: toc
        label: Table of Contents
        type: boolean
      - name: top
        label: Top
        type: number
      - name: body
        label: Body
        type: rich-text

  - name: preface
    label: Preface
    type: collection
    path: src/content/preface/zh-cn
    fields:
      - name: timestamp
        label: Timestamp
        type: date
        required: true
      - name: body
        label: Body
        type: rich-text

  - name: introduction
    label: Introduction
    type: file
    path: src/content/information/zh-cn/introduction.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: policy
    label: Policy
    type: file
    path: src/content/information/zh-cn/policy.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: roll
    label: Roll
    type: file
    path: src/content/information/zh-cn/roll.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text

  - name: chronicle
    label: Chronicle
    type: file
    path: src/content/information/zh-cn/chronicle.yaml
    format: yaml
    fields:
      - name: events
        label: Events
        type: string
        list: true
        fields:
          - name: date
            label: Date
            type: date
          - name: description
            label: Description
            type: string